### ISSUE TITLE
Not working in iOS 10 version 

### ISSUE THREAD

**Issue by nageshkumarmishra** [ahmedabadie/ABNScheduler#17]
Do you have any plans to support for iOS 10 version.

**Comment by ahmdx** [comment]
Hi @nageshkumarmishra, I'm planning to rewrite the library for iOS 10 with backwards compatibility. I was waiting to see if WWDC would bring any changes to the API and I'm currently a bit busy. I hope that it will happen in the coming weeks.

Happy coding :)

**Comment by nageshkumarmishra** [comment]
Thanks !
