### ISSUE TITLE
Use For ios 10 not supported 

### ISSUE THREAD

**Issue by Prashant961992** [ahmedabadie/ABNScheduler#18]
Please provide me Support For  IOS 10.
i implentented sample code for ios 10 below sample Code .

func schedule(fireDate date: Date) -> String? {
        if self.scheduled {
            return nil
        } else {
            if #available(iOS 10.0, *) {
                var calendar = Calendar.current
                calendar.timeZone = NSTimeZone(forSecondsFromGMT: 0) as TimeZone
                calendar.locale = NSLocale(localeIdentifier: "en_US_POSIX") as Locale
                var components: DateComponents? = calendar.dateComponents(([.year, .month, .day, .hour, .minute, .second]), from: date.removeSeconds())
                let day: Int? = components?.day
                let month: Int? = components?.month
                let year: Int? = components?.year
                let hour: Int? = components?.hour
                let minute: Int? = components?.minute
                //        NSInteger second = [[datewithsecond substringFromIndex: [datewithsecond length] - 2] integerValue];
                // //Deliver the notification at sprcific time everyday
                var dateComponents = DateComponents()
                dateComponents.day = day
                dateComponents.month = month
                dateComponents.year = year
                dateComponents.hour = hour
                dateComponents.minute = minute
                
                let trigger = UNCalendarNotificationTrigger(dateMatching: dateComponents, repeats: false)
                let content = UNMutableNotificationContent()
                content.title = String.localizedUserNotificationString(forKey: self.alertBody, arguments: nil)
                content.body = String.localizedUserNotificationString(forKey: self.alertAction!, arguments: nil)
                content.sound = UNNotificationSound.default()
                content.userInfo = self.userInfo
                content.categoryIdentifier = "com.iPll.localNotification"
                content.badge = Int(0) as NSNumber
                
                let request = UNNotificationRequest(identifier: self.identifier, content: content, trigger: trigger)
                let center = UNUserNotificationCenter.current()

                center.add(request, withCompletionHandler: {(_ error: Error?) -> Void in
                    if error == nil {
                        print("add NotificationRequest succeeded!")
                    }
                })
               self.scheduled = true
               return self.identifier
            } else {
                self.localNotification = UILocalNotification()
                self.localNotification.alertBody = self.alertBody
                self.localNotification.alertAction = self.alertAction
                self.localNotification.fireDate = date.removeSeconds()
                self.localNotification.soundName = (self.soundName == nil) ? UILocalNotificationDefaultSoundName : self.soundName;
                self.userInfo[ABNScheduler.identifierKey] = self.identifier as AnyObject?
                self.localNotification.userInfo = self.userInfo
                
                self.soundName = self.localNotification.soundName
                
                if repeatInterval != .None {
                    switch repeatInterval {
                    case .Hourly: self.localNotification.repeatInterval = NSCalendar.Unit.hour
                    case .Daily: self.localNotification.repeatInterval = NSCalendar.Unit.day
                    case .Weekly: self.localNotification.repeatInterval = NSCalendar.Unit.weekOfYear
                    case .Monthly: self.localNotification.repeatInterval = NSCalendar.Unit.month
                    case .Yearly: self.localNotification.repeatInterval = NSCalendar.Unit.year
                    default: break
                    }
                }
                let count = ABNScheduler.scheduledCount()
                if count >= min(ABNScheduler.maximumScheduledNotifications, MAX_ALLOWED_NOTIFICATIONS) {
                    if let farthestNotification = ABNScheduler.farthestLocalNotification() {
                        if farthestNotification > self {
                            farthestNotification.cancel()
                            ABNQueue.queue.push(farthestNotification)
                            self.scheduled = true
                            UIApplication.shared.scheduleLocalNotification(self.localNotification)
                        } else {
                            ABNQueue.queue.push(self)
                        }
                    }
                    return self.identifier
                }
                self.scheduled = true
                UIApplication.shared.scheduleLocalNotification(self.localNotification)
                return self.identifier
            }
        }
    }
using above code i can send notification successfully but i can't send More than 64 Notification so, let me know how send more than 64 Notification in ios 10 and save notification in queue.

Thank You,
regard's
Prashant Prajapati
email : pp961992@gmail.com

**Comment by ahmdx** [comment]
A support for `UserNotifications` is under development. An initial release should be up very soon.
