### ISSUE TITLE
Nothing happen when app in foreground

### ISSUE THREAD

**Issue by zhouhao27** [ahmedabadie/ABNScheduler#19]
It's working if the app is in background (after press Home button). But nothing happen if the app is in foreground. Any idea? Thanks.

**Comment by ahmdx** [comment]
@zhouhao27 the notifications' delivery is completely handled by iOS. If you want something to happen when the app is in the foreground, you should implement your own logic in `application(_:didReceive:)` inside the app delegate.

See: [application(_:didReceive:)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622930-application)
