### ISSUE TITLE
set daily notification

### ISSUE THREAD

**Issue by hamdi-islam** [ahmedabadie/ABNScheduler#3]
i'm trying to fire a notification every day at 22:00pm which will display a quote but it doesn't seem to work for me

```
   `
   let notification = ABNotification(alertBody: "\(author):\n\(text)", identifier: "identifier")
   let identifier = notification.schedule(fireDate: 2200.date)
   notification.snoozeForDays(7)
   notification.soundName = UILocalNotificationDefaultSoundName
```

`

**Comment by ahmdx** [comment]
You are snoozing (rescheduling) the notification to be fired after `7` days from its original fire date. To daily repeat this notification, you have to set its `repeatInterval` to `Repeats.Daily` instead: `notification.repeatInterval = Repeats.Daily`.

If you are trying to schedule more than one notification, create a different identifier for each one to be able to retrieve them individually.

ABNScheduler assigns the default notification sound to the notification by default so you don't need to set it.

`schedule(fireDate:)` should be called after you have set all of the properties of the notification.

```
let notification = ABNotification(alertBody: "\(author):\n\(text)", identifier: "identifier")
notification.repeatInterval = Repeats.Daily
let identifier = notification.schedule(fireDate: 2200.date)
```

Call `ABNScheduler.listScheduledNotifications()` and watch the console where you will find the notification scheduled to be fired daily on 22:00.

**Comment by hamdi-islam** [comment]
ah i see now ! thank you so much i really appreciate it :+1:
